name: build-binaries
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: node18-win-x64
            out: it-asset-manager.exe
          - os: macos-latest
            target: node18-macos-arm64
            out: it-asset-manager-macos
          - os: ubuntu-latest
            target: node18-linux-x64
            out: it-asset-manager-linux
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # use npm install since there's no lockfile
      - run: npm install
      - run: npx pkg . --targets ${{ matrix.target }} --output dist/${{ matrix.out }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out }}
          path: dist/${{ matrix.out }}
